version: '3'
services:
  test-1:
    container_name: test_1
    image: image
    networks:
      testing-net:
        ipv4_address: 172.28.1.1
  
  test-2:
    container_name: test_2
    image: image
    networks:
      testing-net:
        ipv4_address: 172.28.1.2
  
  test-3:
    container_name: test_3
    image: image
    networks:
      testing-net:
        ipv4_address: 172.28.1.3

networks:
  testing-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16